// ========================================
// 100 LOVE QUOTES FOR FATHIMA
// ========================================
const loveQuotes = [
    "Your smile is the first thing I want to see every morning and the last thing I want to see every night.",
    "In a world full of people, my eyes will always search for you.",
    "You are my today, my tomorrow, and my forever.",
    "Every love story is beautiful, but ours is my favorite.",
    "I fell in love with your soul before I even touched your skin.",
    "You are the reason I believe in magic.",
    "My heart knew the moment it met you — you were the one.",
    "Being with you feels like coming home.",
    "You make the ordinary feel extraordinary.",
    "I love the way your eyes light up when you laugh.",
    "Every moment with you is a treasure I hold close to my heart.",
    "You are not just my wife, you are my best friend and soulmate.",
    "The sound of your voice is my favorite melody.",
    "I would choose you in a hundred lifetimes, in a hundred worlds.",
    "You are the missing piece I never knew I needed.",
    "Your kindness inspires me to be a better person every day.",
    "Falling in love with you was the best decision I never made — my heart did it for me.",
    "You are my sunshine on the cloudiest days.",
    "I love you more than words could ever express.",
    "You are the dream I never want to wake up from.",
    "Every day with you is a new adventure I look forward to.",
    "Your laughter is the most beautiful sound in the world.",
    "You complete me in ways I never thought possible.",
    "I am so grateful that the universe brought us together.",
    "You are the poem I always wanted to write.",
    "My love for you grows stronger with each passing day.",
    "You are the calm in my storm.",
    "I see forever when I look into your eyes.",
    "You make my heart do things it never did before.",
    "You are the best part of every day.",
    "I love how you make even the simplest moments feel special.",
    "You are my answered prayer.",
    "The world becomes more beautiful when you're in it.",
    "I never knew what true love was until I met you.",
    "You are the reason my heart beats.",
    "Every second spent with you is a second well spent.",
    "You are the light that guides me through the darkness.",
    "I am hopelessly, irrevocably in love with you.",
    "Your love is the greatest gift I have ever received.",
    "You are my happily ever after.",
    "I love the way you care for everyone around you.",
    "You make the world a better place just by being in it.",
    "My favorite place in the world is right next to you.",
    "You are the melody to my song of life.",
    "I thank God every day for blessing me with you.",
    "You are more beautiful than any sunset or sunrise.",
    "I love you to the moon and back, and then some more.",
    "You are my safe haven, my comfort zone, my home.",
    "Your love gives me the strength to face anything.",
    "You are the queen of my heart, today and always.",
    "I can't imagine my life without your beautiful presence.",
    "You are the reason behind my happiest memories.",
    "Your grace and beauty leave me speechless every single day.",
    "I love the way your hand fits perfectly in mine.",
    "You are not just beautiful on the outside — your soul is pure gold.",
    "Every heartbeat of mine whispers your name.",
    "You turn my ordinary days into extraordinary adventures.",
    "I love how you always know exactly what to say to make me smile.",
    "You are my greatest blessing and my deepest love.",
    "The way you love me makes me believe in miracles.",
    "You are the star that lights up my darkest nights.",
    "I love waking up knowing that you are mine.",
    "Your presence makes everything feel right in the world.",
    "You are the reason I smile for no reason at all.",
    "I love you not only for who you are, but for who I become when I'm with you.",
    "You are the most amazing woman I have ever known.",
    "My love for you is like the ocean — deep, vast, and endless.",
    "You are the heartbeat of our beautiful family.",
    "I love the way your face lights up when you're happy.",
    "You are my definition of perfect.",
    "Every love song reminds me of you.",
    "You are the warmth in my coldest winters.",
    "I love your strength, your courage, and your beautiful heart.",
    "You make falling in love feel like the easiest thing in the world.",
    "You are the miracle I prayed for and received.",
    "I love every version of you — the happy, the sad, the silly, all of you.",
    "You are the reason I believe in forever.",
    "My soul recognized yours long before my eyes ever did.",
    "You are the flowers in my garden of life.",
    "I love how we can talk for hours and never get bored.",
    "You are my compass, always pointing me in the right direction.",
    "Your love is the foundation of everything good in my life.",
    "I love the little things about you that make you uniquely you.",
    "You are the answer to every wish I ever made.",
    "I fall more in love with you every single day.",
    "You are the most precious person in my entire world.",
    "I love the way you look at me like I'm your whole world.",
    "You are the rainbow after every storm in my life.",
    "My heart, my soul, my everything — it all belongs to you.",
    "You are the grace that makes my life beautiful.",
    "I love how you always put others before yourself.",
    "You are the best thing that has ever happened to me.",
    "Every prayer I ever whispered led me to you.",
    "You are the love that I never knew I was searching for.",
    "I love you for all that you are, all that you have been, and all you are yet to be.",
    "You are the peace my restless heart always needed.",
    "I love our little moments more than any grand gesture.",
    "You are my forever and always, my beginning and my end.",
    "Thank you for being the most wonderful wife in the world.",
    "You are the love of my life, Fathima. Happy Birthday, my everything."
];

const loadingQuotes = [
    "Every love story is beautiful, but ours is my favorite...",
    "You are the reason I believe in love...",
    "My heart beats only for you, Fathima...",
    "Getting ready to celebrate the most beautiful soul...",
    "Preparing a world of love, just for you..."
];
